version: 2
jobs:
  build:
    docker:
      - image: nvidia/cuda:9.1-devel-ubuntu16.04

    steps:
      - checkout

      - run:
          name: CMake Build
          command: |
                mkdir build
                cd build
                cmake ..
                make

      - run:
          name: Run tests
          command: |
                cd test
                make
                ./run_test_xuanwu
