version: 2

jobs:
  build:
    docker:
      - image: chnlkw/cpp:cuda

    steps:

      - checkout
          post:
            - git submodule init
            - git submodule update


      - run:
          name: CMake Build
          command: |
                mkdir build
                cd build
                cmake .. -DTEST=ON
                make

      - run:
          name: Run tests
          command: |
                cd test
                make
                ./run_test_xuanwu
