version: 2

jobs:
  build:
    docker:
      - image: chnlkw/cpp:cuda

    steps:

      - checkout

      - run:
          name: checkout submodules
          command: |
               git submodule update --init --recursive

      - run:
          name: CMake Build
          command: |
                mkdir build
                cd build
                cmake .. -DTEST=ON
                make

      - run:
          name: Run tests
          command: |
                cd test
                make
                ./run_test_xuanwu
